// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PadariaWebMvc.Data;

namespace PadariaWebMvc.Migrations
{
    [DbContext(typeof(PadariaWebMvcContext))]
    partial class PadariaWebMvcContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PadariaWebMvc.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int?>("ProductId");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("PadariaWebMvc.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<double>("Valor");

                    b.HasKey("Id");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("PadariaWebMvc.Models.Client", b =>
                {
                    b.HasOne("PadariaWebMvc.Models.Product", "Product")
                        .WithMany("Client")
                        .HasForeignKey("ProductId");
                });
#pragma warning restore 612, 618
        }
    }
}
